ans1:program_1.c
	gcc program_1.c -o program_1
	cat input_1.txt | ./program_1 > ans_1.txt

run1:program_1.c
	gcc program_1.c -o program_1
	cat input_1.txt | ./program_1

ans2:program_2.c
	gcc program_2.c -o program_2
	cat input_2.txt | ./program_2 > ans_2.txt

run2:program_2.c
	gcc program_2.c -o program_2
	cat input_2.txt | ./program_2
clean:
	rm -f program_1 program_2
